# Generated by Django 5.2 on 2025-05-19 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="users_card",
            field=models.PositiveSmallIntegerField(
                blank=True, null=True, verbose_name="User card number"
            ),
        ),
    ]
