# Generated by Django 5.2 on 2025-05-19 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_user_users_card"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="users_card",
            new_name="user_card",
        ),
    ]
