# Generated by Django 5.2 on 2025-05-27 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_rename_users_card_user_user_card"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="user_card",
            field=models.CharField(
                blank=True, max_length=5, null=True, verbose_name="User card"
            ),
        ),
    ]
