# Generated by Django 5.2 on 2025-05-18 12:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Author",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=300, verbose_name="Author name")),
                (
                    "surname",
                    models.CharField(max_length=300, verbose_name="Author surname"),
                ),
                ("birth_date", models.DateTimeField(verbose_name="Author's birthday")),
            ],
            options={
                "verbose_name": "Author",
                "verbose_name_plural": "Authors",
            },
        ),
        migrations.CreateModel(
            name="BookContent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "number",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Content number"
                    ),
                ),
                (
                    "content",
                    models.CharField(max_length=100, verbose_name="Content text"),
                ),
            ],
            options={
                "verbose_name": "Content",
                "verbose_name_plural": "Contents",
            },
        ),
        migrations.CreateModel(
            name="BookFeature",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "feature",
                    models.CharField(
                        choices=[
                            ("Rare", "Rare"),
                            ("Expensive", "Expensive"),
                            ("Popular", "Popular"),
                            ("No_features", "No_features"),
                        ],
                        default="No_features",
                        max_length=11,
                        verbose_name="Book feature",
                    ),
                ),
            ],
            options={
                "verbose_name": "Feature",
                "verbose_name_plural": "Features",
            },
        ),
        migrations.CreateModel(
            name="BookFinance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("price", models.FloatField(default=10000, verbose_name="Book price")),
                (
                    "overdue_day",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="Overdue day for the book"
                    ),
                ),
                (
                    "overdue_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Start date of overdue"
                    ),
                ),
                (
                    "penalty_sum",
                    models.FloatField(default=0, verbose_name="Penalty for overdue"),
                ),
                (
                    "end_overdue",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="End date of overdue"
                    ),
                ),
                ("is_payment_done", models.BooleanField(default=None)),
            ],
            options={
                "verbose_name": "Finance",
                "verbose_name_plural": "Finances",
            },
        ),
        migrations.CreateModel(
            name="BookGenre",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "genre",
                    models.CharField(
                        choices=[
                            ("Adventure", "Adventure"),
                            ("Kids", "Kids"),
                            ("Classic", "Classic"),
                            ("Foreign_language", "Foreign_language"),
                            ("Fantasy", "Fantasy"),
                            ("Science", "Science"),
                            ("Mix", "Mix"),
                        ],
                        default=None,
                        max_length=16,
                        verbose_name="Book genre",
                    ),
                ),
            ],
            options={
                "verbose_name": "Genre",
                "verbose_name_plural": "Genres",
            },
        ),
        migrations.CreateModel(
            name="BookVolume",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "number",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Volume number"
                    ),
                ),
                (
                    "volume",
                    models.PositiveSmallIntegerField(verbose_name="Volume number"),
                ),
            ],
            options={
                "verbose_name": "Volume",
                "verbose_name_plural": "Volumes",
            },
        ),
        migrations.CreateModel(
            name="Library",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=300, verbose_name="Library name")),
                (
                    "main_page",
                    models.TextField(
                        help_text="Main page text", verbose_name="Main page text"
                    ),
                ),
                (
                    "rules_page",
                    models.TextField(
                        help_text="Rules page text", verbose_name="Rules page text"
                    ),
                ),
            ],
            options={
                "verbose_name": "Library",
                "verbose_name_plural": "Libraries",
            },
        ),
        migrations.CreateModel(
            name="BookGeneral",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=300, verbose_name="Book Title")),
                (
                    "description",
                    models.TextField(
                        help_text="Book description", verbose_name="Book description"
                    ),
                ),
                (
                    "age_restriction",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="Age restriction"
                    ),
                ),
                (
                    "rating",
                    models.PositiveIntegerField(default=0, verbose_name="Book rating"),
                ),
                ("is_available", models.BooleanField(default=True)),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="author",
                        to="books.author",
                    ),
                ),
                (
                    "genre",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="book_genre",
                        to="books.bookgenre",
                    ),
                ),
                (
                    "library",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="library",
                        to="books.library",
                    ),
                ),
            ],
            options={
                "verbose_name": "Book",
                "verbose_name_plural": "Books",
            },
        ),
        migrations.CreateModel(
            name="BookDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("edition_year", models.DateTimeField(verbose_name="Edition date")),
                (
                    "page_amount",
                    models.PositiveSmallIntegerField(verbose_name="Amount of pages"),
                ),
                (
                    "taken_by_client",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Date, when Taken by client"
                    ),
                ),
                (
                    "return_date",
                    models.DateTimeField(
                        blank=True,
                        null=True,
                        verbose_name="Date, when shall be return by client",
                    ),
                ),
                ("is_overdue", models.BooleanField(default=False)),
                (
                    "picture",
                    models.ImageField(
                        blank=True,
                        default=None,
                        null=True,
                        upload_to="books/pictures/%Y/%m/%d/",
                        verbose_name="Saved boo picture",
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="client",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "content",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="book_content",
                        to="books.bookcontent",
                    ),
                ),
                (
                    "volume",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="book_volume",
                        to="books.bookcontent",
                    ),
                ),
                (
                    "book_finance",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="book_finance",
                        to="books.bookfinance",
                    ),
                ),
                (
                    "book",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="book_general",
                        to="books.bookgeneral",
                    ),
                ),
            ],
            options={
                "verbose_name": "Book",
                "verbose_name_plural": "Books",
            },
        ),
    ]
