# Generated by Django 5.2 on 2025-05-18 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="author",
            name="birth_date",
            field=models.DateField(verbose_name="Author's birthday"),
        ),
    ]
