# Generated by Django 5.2 on 2025-05-18 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0003_alter_bookdetail_book_finance"),
    ]

    operations = [
        migrations.AddField(
            model_name="bookgeneral",
            name="is_book_popular",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="bookfeature",
            name="feature",
            field=models.CharField(
                choices=[
                    ("Rare", "Rare"),
                    ("Expensive", "Expensive"),
                    ("No_features", "No_features"),
                ],
                default="No_features",
                max_length=11,
                verbose_name="Book feature",
            ),
        ),
    ]
