# Generated by Django 5.2 on 2025-05-18 14:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0004_bookgeneral_is_book_popular_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bookdetail",
            name="book_finance",
        ),
        migrations.AddField(
            model_name="bookfinance",
            name="book",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="book_finance",
                to="books.bookdetail",
            ),
        ),
        migrations.AlterField(
            model_name="bookdetail",
            name="edition_year",
            field=models.DateField(verbose_name="Edition date"),
        ),
    ]
