# Generated by Django 5.2 on 2025-05-18 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0005_remove_bookdetail_book_finance_bookfinance_book_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="bookvolume",
            name="page_amount",
            field=models.PositiveSmallIntegerField(
                blank=True, null=True, verbose_name="Amount of pages"
            ),
        ),
        migrations.AlterField(
            model_name="bookdetail",
            name="page_amount",
            field=models.PositiveSmallIntegerField(
                blank=True, null=True, verbose_name="Amount of pages"
            ),
        ),
    ]
