# Generated by Django 5.2 on 2025-05-18 16:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0006_bookvolume_page_amount_alter_bookdetail_page_amount"),
    ]

    operations = [
        migrations.AddField(
            model_name="bookdetail",
            name="feature",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="book_feature",
                to="books.bookfeature",
            ),
        ),
    ]
