# Generated by Django 5.2 on 2025-05-18 16:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0007_bookdetail_feature"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bookdetail",
            name="volume",
        ),
        migrations.AddField(
            model_name="bookvolume",
            name="book",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="book_volume",
                to="books.bookgeneral",
            ),
        ),
    ]
