# Generated by Django 5.2 on 2025-05-18 16:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0008_remove_bookdetail_volume_bookvolume_book"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bookvolume",
            name="book",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="book_volume",
                to="books.bookdetail",
            ),
        ),
    ]
