# Generated by Django 5.2 on 2025-05-18 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0009_alter_bookvolume_book"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bookvolume",
            name="volume",
        ),
    ]
