# Generated by Django 5.2 on 2025-05-18 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0010_remove_bookvolume_volume"),
    ]

    operations = [
        migrations.DeleteModel(
            name="BookVolume",
        ),
    ]
