# Generated by Django 5.2 on 2025-05-18 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0012_bookvolume"),
    ]

    operations = [
        migrations.DeleteModel(
            name="BookVolume",
        ),
    ]
