# Generated by Django 5.2 on 2025-05-18 16:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0013_delete_bookvolume"),
    ]

    operations = [
        migrations.CreateModel(
            name="BookVolume",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "number",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Volume number"
                    ),
                ),
                (
                    "page_amount",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Amount of pages"
                    ),
                ),
                (
                    "book",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="book_volume",
                        to="books.bookdetail",
                    ),
                ),
            ],
            options={
                "verbose_name": "Volume",
                "verbose_name_plural": "Volumes",
            },
        ),
    ]
