# Generated by Django 5.2 on 2025-05-18 18:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0016_bookvolume"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bookfinance",
            name="book",
        ),
        migrations.AddField(
            model_name="bookdetail",
            name="book_finance",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="book_finance",
                to="books.bookfinance",
            ),
        ),
        migrations.AlterField(
            model_name="bookfinance",
            name="price",
            field=models.FloatField(
                blank=True, default=10000, null=True, verbose_name="Book price"
            ),
        ),
    ]
