# Generated by Django 5.2 on 2025-05-18 18:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0017_remove_bookfinance_book_bookdetail_book_finance_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bookdetail",
            name="book_finance",
        ),
        migrations.AddField(
            model_name="bookfinance",
            name="book",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="book_finance",
                to="books.bookdetail",
            ),
        ),
    ]
