# Generated by Django 5.2 on 2025-05-18 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0018_remove_bookdetail_book_finance_bookfinance_book"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bookfinance",
            name="is_payment_done",
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
    ]
