# Generated by Django 5.2 on 2025-05-19 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0019_alter_bookfinance_is_payment_done"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bookdetail",
            name="taken_by_client",
            field=models.DateTimeField(
                blank=True,
                default=None,
                null=True,
                verbose_name="Date, when Taken by client",
            ),
        ),
        migrations.AlterField(
            model_name="library",
            name="name",
            field=models.CharField(
                default="Library_1", max_length=300, verbose_name="Library name"
            ),
        ),
    ]
