# Generated by Django 5.2 on 2025-05-19 16:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0020_alter_bookdetail_taken_by_client_alter_library_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bookdetail",
            name="content",
            field=models.OneToOneField(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="book_content",
                to="books.bookcontent",
            ),
        ),
    ]
