# Generated by Django 5.2 on 2025-05-19 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0022_alter_bookdetail_book"),
    ]

    operations = [
        migrations.RenameField(
            model_name="bookdetail",
            old_name="book",
            new_name="book_general",
        ),
    ]
