# Generated by Django 5.2 on 2025-05-19 18:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0023_rename_book_bookdetail_book_general"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bookdetail",
            name="content",
            field=models.OneToOneField(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="books.bookcontent",
            ),
        ),
    ]
