# Generated by Django 5.2 on 2025-05-20 17:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0024_alter_bookdetail_content"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bookdetail",
            name="book_general",
            field=models.ForeignKey(
                default=276,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="book_detail",
                to="books.bookgeneral",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="bookdetail",
            name="feature",
            field=models.ForeignKey(
                default=79,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="book_feature",
                to="books.bookfeature",
            ),
            preserve_default=False,
        ),
    ]
