# Generated by Django 5.2 on 2025-05-20 17:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0025_alter_bookdetail_book_general_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bookdetail",
            name="book_general",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="book_detail",
                to="books.bookgeneral",
            ),
        ),
    ]
