# Generated by Django 5.2 on 2025-05-21 16:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0026_alter_bookdetail_book_general"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bookgeneral",
            name="age_restriction",
            field=models.PositiveSmallIntegerField(verbose_name="Age restriction"),
        ),
        migrations.AlterField(
            model_name="bookgeneral",
            name="author",
            field=models.ForeignKey(
                default=389,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="author",
                to="books.author",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="bookgeneral",
            name="library",
            field=models.ForeignKey(
                default=45,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="library",
                to="books.library",
            ),
            preserve_default=False,
        ),
    ]
