# Generated by Django 5.2 on 2025-05-21 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0027_alter_bookgeneral_age_restriction_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="library",
            name="name",
            field=models.CharField(max_length=300, verbose_name="Library name"),
        ),
    ]
