# Generated by Django 5.2 on 2025-05-21 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0028_alter_library_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="library",
            name="name",
            field=models.CharField(
                max_length=300, unique=True, verbose_name="Library name"
            ),
        ),
    ]
