# Generated by Django 5.2 on 2025-05-21 16:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0029_alter_library_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bookgeneral",
            name="genre",
            field=models.ForeignKey(
                default=312,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="book_genre",
                to="books.bookgenre",
            ),
            preserve_default=False,
        ),
    ]
