# Generated by Django 5.2 on 2025-05-21 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0031_alter_bookgeneral_genre"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bookgenre",
            name="genre",
            field=models.CharField(
                choices=[
                    ("Adventure", "Adventure"),
                    ("Kids", "Kids"),
                    ("Classic", "Classic"),
                    ("Foreign_language", "Foreign_language"),
                    ("Fantasy", "Fantasy"),
                    ("Science", "Science"),
                    ("Mix", "Mix"),
                ],
                max_length=16,
                verbose_name="Book genre",
            ),
        ),
    ]
