# Generated by Django 5.2 on 2025-05-21 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0033_alter_bookgeneral_genre"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bookgenre",
            name="genre",
            field=models.CharField(max_length=16, verbose_name="Book genre"),
        ),
    ]
