# Generated by Django 5.2 on 2025-05-21 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0034_alter_bookgenre_genre"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bookgenre",
            name="genre",
            field=models.CharField(verbose_name="Book genre"),
        ),
    ]
