# Generated by Django 5.2 on 2025-05-21 17:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0035_alter_bookgenre_genre"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bookgeneral",
            name="genre",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="genre_book",
                to="books.bookgenre",
            ),
        ),
    ]
