# Generated by Django 5.2 on 2025-05-21 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0036_alter_bookgeneral_genre"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bookgenre",
            name="genre",
            field=models.CharField(blank=True, null=True, verbose_name="Book genre"),
        ),
    ]
