# Generated by Django 5.2 on 2025-05-21 18:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0037_alter_bookgenre_genre"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bookgeneral",
            name="genre",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="genre_book",
                to="books.bookgenre",
            ),
        ),
        migrations.AlterField(
            model_name="bookgenre",
            name="genre",
            field=models.CharField(default=342, verbose_name="Book genre"),
            preserve_default=False,
        ),
    ]
