# Generated by Django 5.2 on 2025-05-21 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0039_alter_bookgenre_genre"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bookdetail",
            name="page_amount",
            field=models.PositiveSmallIntegerField(
                default=100, verbose_name="Amount of pages"
            ),
            preserve_default=False,
        ),
    ]
