# Generated by Django 5.2 on 2025-05-21 19:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0040_alter_bookdetail_page_amount"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bookfinance",
            name="book",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="book_finance",
                to="books.bookdetail",
            ),
        ),
        migrations.AlterField(
            model_name="bookfinance",
            name="price",
            field=models.FloatField(default=1.0, verbose_name="Book price"),
            preserve_default=False,
        ),
    ]
