# Generated by Django 5.2 on 2025-05-22 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0041_alter_bookfinance_book_alter_bookfinance_price"),
    ]

    operations = [
        migrations.RenameField(
            model_name="bookdetail",
            old_name="return_date",
            new_name="due_date",
        ),
    ]
