# Generated by Django 5.2 on 2025-05-22 13:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0042_rename_return_date_bookdetail_due_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bookvolume",
            name="book",
            field=models.ForeignKey(
                default=392,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="book_volume",
                to="books.bookdetail",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="bookvolume",
            name="number",
            field=models.PositiveSmallIntegerField(
                default=2, verbose_name="Volume number"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="bookvolume",
            name="page_amount",
            field=models.PositiveSmallIntegerField(
                default=100, verbose_name="Amount of pages"
            ),
            preserve_default=False,
        ),
    ]
