# Generated by Django 5.2 on 2025-05-22 14:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0043_alter_bookvolume_book_alter_bookvolume_number_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bookdetail",
            name="content",
        ),
        migrations.AddField(
            model_name="bookcontent",
            name="book",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="book_content",
                to="books.bookdetail",
            ),
        ),
        migrations.AddField(
            model_name="bookcontent",
            name="volume",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="volume_content",
                to="books.bookvolume",
            ),
        ),
        migrations.AlterField(
            model_name="bookcontent",
            name="number",
            field=models.CharField(
                default="sd", max_length=100, verbose_name=" Number text"
            ),
            preserve_default=False,
        ),
    ]
