# Generated by Django 5.2 on 2025-05-24 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0044_remove_bookdetail_content_bookcontent_book_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Archive",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=300, verbose_name="Book Title")),
            ],
            options={
                "verbose_name": "Archive",
                "verbose_name_plural": "Archives",
            },
        ),
    ]
