# Generated by Django 5.2 on 2025-05-24 11:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0045_archive"),
    ]

    operations = [
        migrations.AddField(
            model_name="archive",
            name="book",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="archive_book",
                to="books.bookdetail",
            ),
        ),
    ]
