# Generated by Django 5.2 on 2025-05-24 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0046_archive_book"),
    ]

    operations = [
        migrations.AddField(
            model_name="archive",
            name="taken_by_client",
            field=models.DateTimeField(
                blank=True,
                default=None,
                null=True,
                verbose_name="Date, when Taken by client",
            ),
        ),
        migrations.AddField(
            model_name="archive",
            name="user_card",
            field=models.PositiveSmallIntegerField(
                blank=True, null=True, verbose_name="User card number"
            ),
        ),
    ]
