# Generated by Django 5.2 on 2025-05-24 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0047_archive_taken_by_client_archive_user_card"),
    ]

    operations = [
        migrations.AddField(
            model_name="archive",
            name="return_date",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Date, when book returned by client"
            ),
        ),
    ]
