# Generated by Django 5.2 on 2025-05-24 12:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0048_archive_return_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="archive",
            name="book",
        ),
        migrations.AddField(
            model_name="archive",
            name="order",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="archive_order",
                to="books.bookdetail",
            ),
        ),
    ]
