# Generated by Django 5.2 on 2025-05-24 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0049_remove_archive_book_archive_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="archive",
            name="order_continued_times",
            field=models.PositiveSmallIntegerField(
                default=0, verbose_name="Times to continue order"
            ),
        ),
        migrations.AlterField(
            model_name="archive",
            name="taken_by_client",
            field=models.DateTimeField(
                blank=True,
                default=None,
                null=True,
                verbose_name="Date, when book is taken by client",
            ),
        ),
    ]
