# Generated by Django 5.2 on 2025-05-26 12:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0050_archive_order_continued_times_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bookgeneral",
            name="genre",
            field=models.ForeignKey(
                default=389,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="genre_book",
                to="books.bookgenre",
            ),
            preserve_default=False,
        ),
    ]
