# Generated by Django 5.2 on 2025-05-29 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0051_alter_bookgeneral_genre"),
    ]

    operations = [
        migrations.AddField(
            model_name="archive",
            name="is_overdue",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="archive",
            name="payment_date",
            field=models.DateField(
                blank=True, default=None, null=True, verbose_name="Payment date"
            ),
        ),
    ]
