# Generated by Django 5.2 on 2025-05-29 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0052_archive_is_overdue_archive_payment_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="archive",
            name="payed_sum",
            field=models.FloatField(
                blank=True, default=None, null=True, verbose_name="Payment for overdue"
            ),
        ),
    ]
