# Generated by Django 5.2 on 2025-05-29 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0053_archive_payed_sum"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bookfinance",
            name="end_overdue",
        ),
        migrations.RemoveField(
            model_name="bookfinance",
            name="is_payment_done",
        ),
    ]
